In [1]:
import pandas as pd
import numpy as np
import pipes_FCNN as pp_
import pickle

df_ = pd.read_csv('NewDataFrame.csv')



df_ = pp_.myPipe.transform(df_)


#X = X - X.mean()
#X = X/X.std()


In [2]:
df_.head()

Month        Age Occupation  AnnualIncome  MonthlyInhandSalary  \
0    0.0  23.000000  Scientist      19114.12          1824.843333   
1    1.0  23.000000  Scientist      19114.12          4194.170850   
2    2.0  33.307829  Scientist      19114.12          4194.170850   
3    3.0  23.000000  Scientist      19114.12          4194.170850   
4    4.0  23.000000  Scientist      19114.12          1824.843333   

   NumBankAccounts  NumCreditCard  InterestRate  NumofLoan  Delayfromduedate  \
0                3              4             3        4.0                 3   
1                3              4             3        4.0                -1   
2                3              4             3        4.0                 3   
3                3              4             3        4.0                 5   
4                3              4             3        4.0                 6   

   ...  NumCreditInquiries  CreditMix  OutstandingDebt  \
0  ...                 4.0          3           809.98   
1  ...                 4.0          1           809.98   
2  ...                 4.0          1           809.98   
3  ...                 4.0          1           809.98   
4  ...                 4.0          1           809.98   

   CreditUtilizationRatio  PaymentofMinAmount  TotalEMIpermonth  \
0               26.822620                   1         49.574949   
1               31.944960                   1         49.574949   
2               28.609352                   1         49.574949   
3               31.377862                   1         49.574949   
4               24.797347                   1         49.574949   

               PaymentBehaviour MonthlyBalance  CreditScore  \
0   HighspentSmallvaluepayments     312.494089            1   
1    LowspentLargevaluepayments     284.629163            1   
2   LowspentMediumvaluepayments     331.209863            1   
3    LowspentSmallvaluepayments     223.451310            1   
4  HighspentMediumvaluepayments     341.489231            1   

   CreditHistoryYears  
0           22.000000  
1           17.966516  
2           22.000000  
3           22.000000  
4           22.000000  

[5 rows x 21 columns]

In [3]:
Y = df_['CreditScore']

In [4]:
from sklearn.preprocessing import OneHotEncoder
oh = OneHotEncoder()
h_cat_en, h_categories = df_['Occupation'].factorize()
coded = oh.fit_transform(h_cat_en.reshape(-1,1))
proxy = pd.DataFrame(coded.toarray(), index = df_.index, columns = ['1','2','3','4','5','6','7','8','9','10','11','12','13','14',
                                                                          '15','16'])
df_ = pd.concat([df_, proxy], axis = 1)    

h_cats1 = {}
for i in range(len(h_categories)):
    h_cats1[h_categories[i]] = i


with open('oneHotEncoder1.pkl', 'wb') as f:
    pickle.dump(oh,f)

with open('h_cats1.pkl', 'wb') as f:
    pickle.dump(h_cats1,f)


oh2 = OneHotEncoder()
h_cat_en2, h_categories2 = df_['PaymentBehaviour'].factorize()
coded2 = oh2.fit_transform(h_cat_en2.reshape(-1,1))
proxy2 = pd.DataFrame(coded2.toarray(), index = df_.index, columns = ['1','2','3','4','5','6','7'])
df_ = pd.concat([df_, proxy2], axis = 1)
df_ = df_.drop(['PaymentBehaviour','CreditScore','Occupation'], axis = 1)

h_cats2 = {}
for i in range(len(h_categories2)):
    h_cats2[h_categories2[i]] = i


with open('h_cats2.pkl', 'wb') as f:
    pickle.dump(h_cats2,f)
 
    

with open('oneHotEncoder2.pkl', 'wb') as f:
    pickle.dump(oh2,f)

In [5]:
h_categories

Index(['Scientist', 'NoOccupation', 'Teacher', 'Engineer', 'Entrepreneur',
       'Developer', 'Lawyer', 'MediaManager', 'Doctor', 'Journalist',
       'Manager', 'Accountant', 'Musician', 'Mechanic', 'Writer', 'Architect'],
      dtype='object')

In [6]:
h_cat_en.shape

(100000,)

In [7]:
oh.transform([[0]]).toarray()

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [8]:
h_cats1 = {}
for i in range(len(h_categories)):
    h_cats1[h_categories[i]] = i

In [9]:
h_cats1['MediaManager']

7

In [10]:
oh.transform([[7]]).toarray()

array([[0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [11]:
h_cats = {}
for i in range(len(h_categories)):
    h_cats[h_categories[i]] = i
    

In [12]:
[h_cats['Scientist']]

[0]

In [13]:
occ_encoded = oh.transform([[h_cats1['Scientist']]]).toarray()
occ_encoded

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [17]:
v = np.concatenate([v,occ_encoded[0]])

In [16]:
v = [1,2,3,4,5] 
v = np.array(v)

In [18]:
v

array([1., 2., 3., 4., 5., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0.])

In [19]:
df_.head()

Month        Age  AnnualIncome  MonthlyInhandSalary  NumBankAccounts  \
0    0.0  23.000000      19114.12          1824.843333                3   
1    1.0  23.000000      19114.12          4194.170850                3   
2    2.0  33.307829      19114.12          4194.170850                3   
3    3.0  23.000000      19114.12          4194.170850                3   
4    4.0  23.000000      19114.12          1824.843333                3   

   NumCreditCard  InterestRate  NumofLoan  Delayfromduedate  \
0              4             3        4.0                 3   
1              4             3        4.0                -1   
2              4             3        4.0                 3   
3              4             3        4.0                 5   
4              4             3        4.0                 6   

   NumofDelayedPayment  ...   14   15   16    1    2    3    4    5    6    7  
0             7.000000  ...  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  
1            13.220499  ...  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  
2             7.000000  ...  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  
3             4.000000  ...  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  
4            13.220499  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  

[5 rows x 41 columns]

In [20]:
X = df_
X.head()

Month        Age  AnnualIncome  MonthlyInhandSalary  NumBankAccounts  \
0    0.0  23.000000      19114.12          1824.843333                3   
1    1.0  23.000000      19114.12          4194.170850                3   
2    2.0  33.307829      19114.12          4194.170850                3   
3    3.0  23.000000      19114.12          4194.170850                3   
4    4.0  23.000000      19114.12          1824.843333                3   

   NumCreditCard  InterestRate  NumofLoan  Delayfromduedate  \
0              4             3        4.0                 3   
1              4             3        4.0                -1   
2              4             3        4.0                 3   
3              4             3        4.0                 5   
4              4             3        4.0                 6   

   NumofDelayedPayment  ...   14   15   16    1    2    3    4    5    6    7  
0             7.000000  ...  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  
1            13.220499  ...  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  
2             7.000000  ...  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  
3             4.000000  ...  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  
4            13.220499  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  

[5 rows x 41 columns]

In [21]:
from sklearn.preprocessing import StandardScaler
import pickle
mms = StandardScaler()
X = mms.fit_transform(X)


with open('scaler.pkl', 'wb') as f:
    pickle.dump(mms,f)

In [22]:
X.shape

(100000, 41)

# Создание проверочного набора (Create a validation set)

In [23]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train,  Y_test = train_test_split(X, Y, test_size = 0.6, random_state = 0)

In [24]:
X_train.shape, Y_train.shape

((40000, 41), (40000,))

In [25]:
X_train.shape[1]

41

In [27]:
import tensorflow as tf
from tensorflow.keras import models
from tensorflow.keras import layers

model = models.Sequential()

model.add(layers.Dense(256, activation="relu", input_shape = (X_train.shape[1],),)) 
#model.add(layers.Dropout(0.4))

model.add(layers.Dense(128, activation="relu"))
model.add(layers.Dense(64, activation="relu"))

model.add(layers.Dense(3, activation="softmax"))

# Компиляция модели
model.compile(optimizer=tf.keras.optimizers.Adam(1e-3),
              loss="sparse_categorical_crossentropy",
              metrics=["accuracy"])


#'categorical_crossentropy' works on one-hot encoded target, while 'sparse_categorical_crossentropy' works on integer target.


In [29]:
history = model.fit(X_train, Y_train, validation_data = (X_test, Y_test), 
                    epochs=15, batch_size=512)

Epoch 1/15
79/79 [==============================] - 1s 11ms/step - loss: 0.3301 - accuracy: 0.8609 - val_loss: 1.1551 - val_accuracy: 0.6219
Epoch 2/15
79/79 [==============================] - 1s 10ms/step - loss: 0.3279 - accuracy: 0.8631 - val_loss: 1.1714 - val_accuracy: 0.6277
Epoch 3/15
79/79 [==============================] - 1s 11ms/step - loss: 0.3219 - accuracy: 0.8636 - val_loss: 1.1870 - val_accuracy: 0.6209
Epoch 4/15
79/79 [==============================] - 1s 12ms/step - loss: 0.3274 - accuracy: 0.8635 - val_loss: 1.1937 - val_accuracy: 0.6274
Epoch 5/15
79/79 [==============================] - 6s 71ms/step - loss: 0.3094 - accuracy: 0.8711 - val_loss: 1.2353 - val_accuracy: 0.6274
Epoch 6/15
79/79 [==============================] - 7s 93ms/step - loss: 0.3030 - accuracy: 0.8745 - val_loss: 1.2620 - val_accuracy: 0.6261
Epoch 7/15
79/79 [==============================] - 1s 11ms/step - loss: 0.2986 - accuracy: 0.8775 - val_loss: 1.2587 - val_accuracy: 0.6260
Epoch 8/15
79

In [27]:
model.save('creditscore.h5')

In [ ]:
#loaded_model = tf.keras.models.load_model('creditscore.h5')

In [46]:
from sklearn.metrics import confusion_matrix, f1_score

In [47]:
pr = model.predict(X_test)>0.5

1875/1875 [==============================] - 14s 4ms/step


In [52]:
f1_score (Y_test, pr,average='macro')

ValueError: Classification metrics can't handle a mix of multiclass and multilabel-indicator targets

In [11]:
confusion_matrix(Y_test, pr)

array([[29764,  5664],
       [ 6299,  8273]], dtype=int64)

In [31]:
with open('h_cats1.pkl' , 'rb') as f:
    some_cats = pickle.load(f)

In [32]:
some_cats

{'Scientist': 0,
 'NoOccupation': 1,
 'Teacher': 2,
 'Engineer': 3,
 'Entrepreneur': 4,
 'Developer': 5,
 'Lawyer': 6,
 'MediaManager': 7,
 'Doctor': 8,
 'Journalist': 9,
 'Manager': 10,
 'Accountant': 11,
 'Musician': 12,
 'Mechanic': 13,
 'Writer': 14,
 'Architect': 15}