In [18]:
from sklearn.pipeline import Pipeline
import pipes_ as pp
import pandas as pd
from matplotlib import pyplot as plt
import numpy as np
from sklearn.metrics import confusion_matrix, precision_score, \
              recall_score, f1_score, precision_recall_curve, roc_curve, roc_auc_score, \
              auc, mean_squared_error
from sklearn.metrics import confusion_matrix, precision_score, \
              recall_score, f1_score, precision_recall_curve, roc_curve, roc_auc_score, \
              auc, mean_squared_error, accuracy_score

# 1.We review the information. Preparing data for processing format

In [19]:
df_ = pd.read_csv('NewDataFrame.csv')


In [20]:
#df_.rename({"Unnamed: 0":"a"}, axis="columns", inplace=True)
#df_.drop(["a"], axis=1, inplace=True)

In [21]:
df_

Month        Age Occupation  AnnualIncome  MonthlyInhandSalary  \
0       January  23.000000  Scientist      19114.12          1824.843333   
1      February  23.000000  Scientist      19114.12          4194.170850   
2         March  33.307829  Scientist      19114.12          4194.170850   
3         April  23.000000  Scientist      19114.12          4194.170850   
4           May  23.000000  Scientist      19114.12          1824.843333   
...         ...        ...        ...           ...                  ...   
99995     April  25.000000   Mechanic      39628.99          3359.415833   
99996       May  25.000000   Mechanic      39628.99          3359.415833   
99997      June  25.000000   Mechanic      39628.99          3359.415833   
99998      July  25.000000   Mechanic      39628.99          3359.415833   
99999    August  25.000000   Mechanic      39628.99          3359.415833   

       NumBankAccounts  NumCreditCard  InterestRate  NumofLoan  \
0                    3              4             3        4.0   
1                    3              4             3        4.0   
2                    3              4             3        4.0   
3                    3              4             3        4.0   
4                    3              4             3        4.0   
...                ...            ...           ...        ...   
99995                4              6             7        2.0   
99996                4              6             7        2.0   
99997                4              6             0        2.0   
99998                4              6             7        2.0   
99999                4              6             7        2.0   

       Delayfromduedate  ...  NumCreditInquiries    CreditMix OutstandingDebt  \
0                     3  ...                 4.0  NoCreditMix          809.98   
1                    -1  ...                 4.0         Good          809.98   
2                     3  ...                 4.0         Good          809.98   
3                     5  ...                 4.0         Good          809.98   
4                     6  ...                 4.0         Good          809.98   
...                 ...  ...                 ...          ...             ...   
99995                23  ...                 3.0  NoCreditMix          502.38   
99996                18  ...                 3.0  NoCreditMix          502.38   
99997                27  ...                 3.0         Good          502.38   
99998                20  ...                 3.0         Good          502.38   
99999                18  ...                 3.0         Good          502.38   

       CreditUtilizationRatio  PaymentofMinAmount TotalEMIpermonth  \
0                   26.822620                  No        49.574949   
1                   31.944960                  No        49.574949   
2                   28.609352                  No        49.574949   
3                   31.377862                  No        49.574949   
4                   24.797347                  No        49.574949   
...                       ...                 ...              ...   
99995               34.663572                  No        35.104023   
99996               40.565631                  No        35.104023   
99997               41.255522                  No        35.104023   
99998               33.638208                  No        35.104023   
99999               34.192463                  No        35.104023   

                   PaymentBehaviour MonthlyBalance  CreditScore  \
0       HighspentSmallvaluepayments     312.494089         Good   
1        LowspentLargevaluepayments     284.629163         Good   
2       LowspentMediumvaluepayments     331.209863         Good   
3        LowspentSmallvaluepayments     223.451310         Good   
4      HighspentMediumvaluepayments     341.489231         Good   
...                             ...            ...          ...   
99995   HighspentLarg

In [22]:
df_['PaymentBehaviour'].value_counts()

LowspentSmallvaluepayments      25513
HighspentMediumvaluepayments    17540
LowspentMediumvaluepayments     13861
HighspentLargevaluepayments     13721
HighspentSmallvaluepayments     11340
LowspentLargevaluepayments      10425
NoPaymentBehaviour               7600
Name: PaymentBehaviour, dtype: int64

In [23]:
df_ = pp.myPipe.transform(df_)

In [24]:
df_.head()

Month        Age  AnnualIncome  MonthlyInhandSalary  NumBankAccounts  \
0    0.0  23.000000      19114.12          1824.843333                3   
1    1.0  23.000000      19114.12          4194.170850                3   
2    2.0  33.307829      19114.12          4194.170850                3   
3    3.0  23.000000      19114.12          4194.170850                3   
4    4.0  23.000000      19114.12          1824.843333                3   

   NumCreditCard  InterestRate  NumofLoan  Delayfromduedate  \
0              4             3        4.0                 3   
1              4             3        4.0                -1   
2              4             3        4.0                 3   
3              4             3        4.0                 5   
4              4             3        4.0                 6   

   NumofDelayedPayment  ...  Occupation_Scientist  Occupation_Teacher  \
0             7.000000  ...                     1                   0   
1            13.220499  ...                     1                   0   
2             7.000000  ...                     1                   0   
3             4.000000  ...                     1                   0   
4            13.220499  ...                     1                   0   

   Occupation_Writer    1    2    3    4    5    6    7  
0                  0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  
1                  0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  
2                  0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  
3                  0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  
4                  0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  

[5 rows x 43 columns]

# Separation of the target variable

In [25]:
X = df_.drop(['CreditScore','PaymentBehaviour'], axis = 1)

In [26]:
Y = df_['CreditScore']

In [27]:
X.shape

(100000, 41)

In [28]:
X.head()

Month        Age  AnnualIncome  MonthlyInhandSalary  NumBankAccounts  \
0    0.0  23.000000      19114.12          1824.843333                3   
1    1.0  23.000000      19114.12          4194.170850                3   
2    2.0  33.307829      19114.12          4194.170850                3   
3    3.0  23.000000      19114.12          4194.170850                3   
4    4.0  23.000000      19114.12          1824.843333                3   

   NumCreditCard  InterestRate  NumofLoan  Delayfromduedate  \
0              4             3        4.0                 3   
1              4             3        4.0                -1   
2              4             3        4.0                 3   
3              4             3        4.0                 5   
4              4             3        4.0                 6   

   NumofDelayedPayment  ...  Occupation_Scientist  Occupation_Teacher  \
0             7.000000  ...                     1                   0   
1            13.220499  ...                     1                   0   
2             7.000000  ...                     1                   0   
3             4.000000  ...                     1                   0   
4            13.220499  ...                     1                   0   

   Occupation_Writer    1    2    3    4    5    6    7  
0                  0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  
1                  0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  
2                  0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  
3                  0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  
4                  0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  

[5 rows x 41 columns]

# Создание проверочного набора (Create a validation set)

In [29]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train,  Y_test = train_test_split(X, Y, test_size = 0.4, random_state = 0)

In [30]:
X_train.shape, Y_train.shape

((60000, 41), (60000,))

In [75]:
#X_train.shape, Y_train.shape

In [76]:
#from sklearn.preprocessing import StandardScaler
#mms = StandardScaler()
#X = mms.fit_transform(X)

#from sklearn.preprocessing import MinMaxScaler
#mms = MinMaxScaler()
#X = mms.fit_transform(X_train)



#with open('scaler.pickle', 'wb') as f:
#    pickle.dump(X,f)


#ЭТИ СТРОЧКИ НАДО ДЛЯ ПРИЛОЖЕНИЯ НАШЕГО ОТДЕЛЬНО ДЛЯ ВСЕГО!!!!!

# a. ML With Teacher

# Version1

In [31]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV

In [32]:
tree = DecisionTreeClassifier()   

In [33]:
paramgrid = { 'max_depth' :[5,6,8,13,20], 'min_samples_split':[11,13,15,18], 'max_features':[4,15,20,24,26]} 

In [34]:
GS_cv = GridSearchCV(tree,param_grid = paramgrid, cv = 3,scoring = 'f1_macro')
# cv - количество разбиений
# we should use scoring = 'f1_macro!!!!!!!

In [35]:
GS_cv.fit(X_train,Y_train)

GridSearchCV(cv=3, estimator=DecisionTreeClassifier(),
             param_grid={'max_depth': [5, 6, 8, 13, 20],
                         'max_features': [4, 15, 20, 24, 26],
                         'min_samples_split': [11, 13, 15, 18]},
             scoring='f1_macro')

In [36]:
GS_cv.best_params_

{'max_depth': 8, 'max_features': 26, 'min_samples_split': 18}

In [37]:
best_gs_tree=GS_cv.best_estimator_

In [38]:
best_gs_tree.score(X_test,Y_test)

0.688125

In [39]:
best_gs_tree.score(X_train,Y_train)

0.7029666666666666

In [40]:
from sklearn.metrics import f1_score
pred = best_gs_tree.predict(X_test)
f1_score = (Y_test,pred)

In [41]:
from sklearn.model_selection import cross_val_score

In [42]:
cs = cross_val_score(best_gs_tree,X_train,Y_train, cv= 6, scoring = 'f1_macro')

In [43]:
cs

array([0.66987098, 0.66240898, 0.65932994, 0.67147287, 0.66669707,
       0.68133684])

In [130]:
cs.mean()

0.6707396323565188

In [131]:
#tree_cl = DecisionTreeClassifier(max_depth=7, min_samples_split=2, min_samples_leaf=1,random_state=0)
#tree_cl.fit(X_train, Y_train)

DecisionTreeClassifier(max_depth=7, random_state=0)

In [133]:
#tree_cl.score(X_test,Y_test), tree_cl.score(X_train, Y_train)

(0.689475, 0.7002333333333334)

# Version2

# Cross - Validation with decision tree

In [46]:
tree_cl = DecisionTreeClassifier(max_depth=7, min_samples_split=2, min_samples_leaf=1,random_state=0)
tree_cl.fit(X_train, Y_train)

DecisionTreeClassifier(max_depth=7, random_state=0)

In [47]:
tree_cl.score(X_test,Y_test), tree_cl.score(X_train, Y_train)

(0.689475, 0.7002333333333334)

In [48]:
from sklearn.model_selection import cross_val_score, cross_val_predict

In [49]:
#передаем наш классификатор обученный, и наше множество,на котором учим.cv - то сколько разбиений мы хотим делать
# scoring='roc_auc'
# we pass our trained classifier, and our set on which we learn. cv - how many partitions we want to do
score = cross_val_score(tree_cl, X_train, Y_train, cv=5) 

In [50]:
# получили 5 оценок из множества X, Y
#received 5 ratings from the set X, Y
score

array([0.69491667, 0.68691667, 0.6915    , 0.68791667, 0.69566667])

In [51]:
score.mean()

0.6913833333333332

In [58]:
from sklearn.tree import export_graphviz

In [65]:
export_graphviz (tree_cl, out_file = 'creditscore_tree.dot', max_depth=2, feature_names=None, class_names=None, label='all', filled=True, leaves_parallel=False, impurity=True, node_ids=False, proportion=False, rotate=False, rounded=True, special_characters=False, precision=3)

# param rounded: When set to True, draw node boxes with rounded corners.
# param filled:  When set to True, paint nodes to indicate majority class for classification,
#                extremity of values for regression, or purity of node for multi-output.

In [66]:
!dot -Tpng creditscore_tree.dot -o creditscore_tree.png

# Отбор случайным лесом (Selection by random forest)

# Version1

In [186]:
from sklearn.ensemble import RandomForestClassifier
rf_clf = RandomForestClassifier() 

In [187]:
paramgrid = { 'n_estimators' :[10,20,30,40,100], 'max_depth':[5,15,19], 'criterion':['gini', 'entropy']}   

In [188]:
GS_cv = GridSearchCV(rf_clf,param_grid = paramgrid, cv = 3,scoring = 'f1_macro')
# cv - количество разбиений

In [189]:
GS_cv.fit(X_train, Y_train)

GridSearchCV(cv=3, estimator=RandomForestClassifier(),
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [5, 15, 19],
                         'n_estimators': [10, 20, 30, 40, 100]},
             scoring='f1')

In [190]:
GS_cv.best_params_

{'criterion': 'gini', 'max_depth': 19, 'n_estimators': 100}

In [51]:
best_gs_tree=GS_cv.best_estimator_

In [53]:
best_gs_tree.score(X_test,Y_test)

0.85032

In [54]:
best_gs_tree.score(X_train, Y_train)

0.95326

In [55]:
from sklearn.metrics import f1_score
pred = best_gs_tree.predict(X_test)
f1_score = (Y_test,pred)

In [56]:
cs = cross_val_score(best_gs_tree,X_train, Y_train, cv= 5, scoring = 'f1_macro')

In [57]:
cs

array([0.72163444, 0.71298532, 0.71964517, 0.71974991, 0.72586588])

In [58]:
cs.mean()

0.719976144015885

# Version2

In [165]:

randfor_cl = RandomForestClassifier(n_estimators=600, max_depth=5, min_samples_split=2, min_samples_leaf=1, random_state = 0)
randfor_cl.fit(X_train, Y_train)
randfor_cl.feature_importances_


array([4.46953169e-03, 2.63559685e-03, 8.69869281e-03, 4.84615416e-03,
       4.57868013e-02, 5.85697074e-02, 1.43232981e-01, 3.18621702e-02,
       8.63350662e-02, 2.51335648e-02, 3.31470397e-02, 6.50480597e-02,
       1.90523548e-01, 1.94193004e-01, 5.10768653e-04, 6.16939336e-02,
       4.10967956e-03, 1.36748660e-03, 5.91066342e-03, 3.00010927e-02,
       2.30938754e-05, 2.17796443e-05, 3.95808728e-05, 4.34955070e-05,
       5.72739689e-05, 4.87331889e-05, 6.56269208e-05, 3.12278717e-05,
       4.51522555e-05, 2.95096171e-05, 8.79116725e-05, 8.08539492e-05,
       7.99982748e-05, 2.96288536e-05, 5.20203825e-05, 9.46109459e-05,
       1.64982304e-05, 4.83671871e-05, 5.47169403e-04, 1.11580243e-04,
       2.26492770e-05, 3.28124570e-04, 1.95706636e-05])

In [166]:
randfor_cl.score(X_test,Y_test), randfor_cl.score(X_train, Y_train)

(0.6629475992943308, 0.6686692823279385)

# save model

In [ ]:
import pickle
with open('data.pickle', 'wb') as f:
     pickle.dump(randfor_cl, f)

In [ ]:
with open('data.pickle', 'rb') as f:
     new_randfor_cl = pickle.load(f)