In [55]:
import pandas as pd
import numpy as np
import pipes_FCNN as pp_
import pickle

df_ = pd.read_csv('NewDataFrame.csv')



df_ = pp_.myPipe.transform(df_)


#X = X - X.mean()
#X = X/X.std()


In [56]:
df_.columns

Index(['Month', 'Age', 'Occupation', 'AnnualIncome', 'MonthlyInhandSalary',
       'NumBankAccounts', 'NumCreditCard', 'InterestRate', 'NumofLoan',
       'Delayfromduedate', 'NumofDelayedPayment', 'NumCreditInquiries',
       'CreditMix', 'OutstandingDebt', 'CreditUtilizationRatio',
       'PaymentofMinAmount', 'TotalEMIpermonth', 'PaymentBehaviour',
       'MonthlyBalance', 'CreditScore', 'CreditHistoryYears'],
      dtype='object')

In [57]:
df_.head()

Month        Age Occupation  AnnualIncome  MonthlyInhandSalary  \
0    0.0  23.000000  Scientist      19114.12          1824.843333   
1    1.0  23.000000  Scientist      19114.12          4194.170850   
2    2.0  33.307829  Scientist      19114.12          4194.170850   
3    3.0  23.000000  Scientist      19114.12          4194.170850   
4    4.0  23.000000  Scientist      19114.12          1824.843333   

   NumBankAccounts  NumCreditCard  InterestRate  NumofLoan  Delayfromduedate  \
0                3              4             3        4.0                 3   
1                3              4             3        4.0                -1   
2                3              4             3        4.0                 3   
3                3              4             3        4.0                 5   
4                3              4             3        4.0                 6   

   ...  NumCreditInquiries  CreditMix  OutstandingDebt  \
0  ...                 4.0          3           809.98   
1  ...                 4.0          1           809.98   
2  ...                 4.0          1           809.98   
3  ...                 4.0          1           809.98   
4  ...                 4.0          1           809.98   

   CreditUtilizationRatio  PaymentofMinAmount  TotalEMIpermonth  \
0               26.822620                   1         49.574949   
1               31.944960                   1         49.574949   
2               28.609352                   1         49.574949   
3               31.377862                   1         49.574949   
4               24.797347                   1         49.574949   

               PaymentBehaviour MonthlyBalance  CreditScore  \
0   HighspentSmallvaluepayments     312.494089            1   
1    LowspentLargevaluepayments     284.629163            1   
2   LowspentMediumvaluepayments     331.209863            1   
3    LowspentSmallvaluepayments     223.451310            1   
4  HighspentMediumvaluepayments     341.489231            1   

   CreditHistoryYears  
0           22.000000  
1           17.966516  
2           22.000000  
3           22.000000  
4           22.000000  

[5 rows x 21 columns]

In [58]:
Y = df_['CreditScore']

In [59]:
from sklearn.preprocessing import OneHotEncoder
oh = OneHotEncoder()
h_cat_en, h_categories = df_['Occupation'].factorize()
coded = oh.fit_transform(h_cat_en.reshape(-1,1))
proxy = pd.DataFrame(coded.toarray(), index = df_.index, columns = ['1','2','3','4','5','6','7','8','9','10','11','12','13','14',
                                                                          '15','16'])
df_ = pd.concat([df_, proxy], axis = 1)    

h_cats1 = {}
for i in range(len(h_categories)):
    h_cats1[h_categories[i]] = i


with open('oneHotEncoder1.pkl', 'wb') as f:
    pickle.dump(oh,f)

with open('h_cats1.pkl', 'wb') as f:
    pickle.dump(h_cats1,f)


oh2 = OneHotEncoder()
h_cat_en2, h_categories2 = df_['PaymentBehaviour'].factorize()
coded2 = oh2.fit_transform(h_cat_en2.reshape(-1,1))
proxy2 = pd.DataFrame(coded2.toarray(), index = df_.index, columns = ['17','18','19','20','21','22','23'])
df_ = pd.concat([df_, proxy2], axis = 1)
df_ = df_.drop(['PaymentBehaviour','CreditScore','Occupation'], axis = 1)

h_cats2 = {}
for i in range(len(h_categories2)):
    h_cats2[h_categories2[i]] = i


with open('h_cats2.pkl', 'wb') as f:
    pickle.dump(h_cats2,f)
 
    

with open('oneHotEncoder2.pkl', 'wb') as f:
    pickle.dump(oh2,f)

In [60]:
h_categories2

Index(['HighspentSmallvaluepayments', 'LowspentLargevaluepayments',
       'LowspentMediumvaluepayments', 'LowspentSmallvaluepayments',
       'HighspentMediumvaluepayments', 'NoPaymentBehaviour',
       'HighspentLargevaluepayments'],
      dtype='object')

In [61]:
h_cat_en.shape

(100000,)

In [62]:
oh.transform([[0]]).toarray()

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [63]:
h_cats1 = {}
for i in range(len(h_categories)):
    h_cats1[h_categories[i]] = i

In [64]:
h_cats1['MediaManager']

7

In [65]:
oh.transform([[7]]).toarray()

array([[0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [84]:
i=int('1')
type(i)

int

In [66]:
h_cats = {}
for i in range(len(h_categories)):
    h_cats[h_categories[i]] = i
    

In [67]:
[h_cats['Scientist']]

[0]

In [68]:
occ_encoded = oh.transform([[h_cats1['Scientist']]]).toarray()
occ_encoded

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [69]:
v = np.concatenate([v,occ_encoded[0]])

NameError: name 'v' is not defined

In [70]:
v = [1,2,3,4,5] 
v = np.array(v)

In [71]:
v

array([1, 2, 3, 4, 5])

In [72]:
df_.head()

Month        Age  AnnualIncome  MonthlyInhandSalary  NumBankAccounts  \
0    0.0  23.000000      19114.12          1824.843333                3   
1    1.0  23.000000      19114.12          4194.170850                3   
2    2.0  33.307829      19114.12          4194.170850                3   
3    3.0  23.000000      19114.12          4194.170850                3   
4    4.0  23.000000      19114.12          1824.843333                3   

   NumCreditCard  InterestRate  NumofLoan  Delayfromduedate  \
0              4             3        4.0                 3   
1              4             3        4.0                -1   
2              4             3        4.0                 3   
3              4             3        4.0                 5   
4              4             3        4.0                 6   

   NumofDelayedPayment  ...   14   15   16   17   18   19   20   21   22   23  
0             7.000000  ...  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  
1            13.220499  ...  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  
2             7.000000  ...  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  
3             4.000000  ...  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  
4            13.220499  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  

[5 rows x 41 columns]

In [73]:
X = df_
X.columns

Index(['Month', 'Age', 'AnnualIncome', 'MonthlyInhandSalary',
       'NumBankAccounts', 'NumCreditCard', 'InterestRate', 'NumofLoan',
       'Delayfromduedate', 'NumofDelayedPayment', 'NumCreditInquiries',
       'CreditMix', 'OutstandingDebt', 'CreditUtilizationRatio',
       'PaymentofMinAmount', 'TotalEMIpermonth', 'MonthlyBalance',
       'CreditHistoryYears', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10',
       '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22',
       '23'],
      dtype='object')

In [74]:
from sklearn.preprocessing import StandardScaler
import pickle
mms = StandardScaler()
X = mms.fit_transform(X)


with open('scaler.pkl', 'wb') as f:
    pickle.dump(mms,f)

In [75]:
X.shape

(100000, 41)

# Создание проверочного набора (Create a validation set)

In [76]:
oh = OneHotEncoder()
h_cat_en, h_categories = Y.factorize()
coded = oh.fit_transform(h_cat_en.reshape(-1,1))
Y = pd.DataFrame(coded.toarray(), index = df_.index, columns = ['1','2','3'])


from sklearn.model_selection import train_test_split

X_train, X_test, Y_train,  Y_test = train_test_split(X, Y, test_size = 0.4, random_state = 0)

In [77]:
X_train.shape, Y_train.shape

((60000, 41), (60000, 3))

In [78]:
X_train

array([[-1.23959081e+00,  1.10105603e+00, -7.30134620e-02, ...,
         2.16823760e+00, -2.86794495e-01, -3.98786392e-01],
       [ 6.49309470e-01,  1.02375469e-13, -7.94054669e-02, ...,
        -4.61204068e-01, -2.86794495e-01, -3.98786392e-01],
       [-1.23959081e+00,  9.12715291e-01, -1.12580627e-01, ...,
        -4.61204068e-01, -2.86794495e-01, -3.98786392e-01],
       ...,
       [ 1.12153454e+00, -9.70692086e-01, -9.83032033e-02, ...,
        -4.61204068e-01, -2.86794495e-01, -3.98786392e-01],
       [-1.23959081e+00,  2.04275972e+00, -1.08221769e-01, ...,
        -4.61204068e-01, -2.86794495e-01, -3.98786392e-01],
       [ 6.49309470e-01, -5.88450240e-02, -1.16574605e-01, ...,
        -4.61204068e-01, -2.86794495e-01, -3.98786392e-01]])

In [24]:
X_train.shape[1]

41

In [79]:
import tensorflow as tf
from tensorflow.keras import models
from tensorflow.keras import layers

model = models.Sequential()

model.add(layers.Dense(256, activation="relu", input_shape = (X_train.shape[1],),)) 
#model.add(layers.Dropout(0.4))

model.add(layers.Dense(256, activation="relu"))

model.add(layers.Dense(256, activation="relu"))
model.add(layers.Dense(128, activation="relu"))


model.add(layers.Dense(64, activation="relu"))

model.add(layers.Dense(3, activation="softmax"))

# Компиляция модели
model.compile(optimizer=tf.keras.optimizers.Adam(1e-3),
              loss="categorical_crossentropy",
              metrics=["accuracy"])


#'categorical_crossentropy' works on one-hot encoded target, while 'sparse_categorical_crossentropy' works on integer target.


In [80]:
history = model.fit(X_train, Y_train, validation_data = (X_test, Y_test), 
                    epochs=50, batch_size=512)

Epoch 1/50
118/118 [==============================] - 1s 5ms/step - loss: 0.7877 - accuracy: 0.6287 - val_loss: 0.7564 - val_accuracy: 0.6428
Epoch 2/50
118/118 [==============================] - 1s 5ms/step - loss: 0.7275 - accuracy: 0.6600 - val_loss: 0.7349 - val_accuracy: 0.6532
Epoch 3/50
118/118 [==============================] - 1s 5ms/step - loss: 0.7060 - accuracy: 0.6719 - val_loss: 0.7140 - val_accuracy: 0.6673
Epoch 4/50
118/118 [==============================] - 1s 5ms/step - loss: 0.6916 - accuracy: 0.6797 - val_loss: 0.7100 - val_accuracy: 0.6674
Epoch 5/50
118/118 [==============================] - 1s 5ms/step - loss: 0.6821 - accuracy: 0.6859 - val_loss: 0.7103 - val_accuracy: 0.6692
Epoch 6/50
118/118 [==============================] - 1s 5ms/step - loss: 0.6745 - accuracy: 0.6910 - val_loss: 0.7134 - val_accuracy: 0.6670
Epoch 7/50
118/118 [==============================] - 1s 5ms/step - loss: 0.6656 - accuracy: 0.6950 - val_loss: 0.7160 - val_accuracy: 0.6700
Epoch 

In [82]:
model.save('creditscore.h5')

In [ ]:
#loaded_model = tf.keras.models.load_model('creditscore.h5')

In [46]:
from sklearn.metrics import confusion_matrix, f1_score

In [47]:
pr = model.predict(X_test)>0.5

1875/1875 [==============================] - 14s 4ms/step


In [52]:
f1_score (Y_test, pr,average='macro')

ValueError: Classification metrics can't handle a mix of multiclass and multilabel-indicator targets

In [11]:
confusion_matrix(Y_test, pr)

array([[29764,  5664],
       [ 6299,  8273]], dtype=int64)

In [31]:
with open('h_cats1.pkl' , 'rb') as f:
    some_cats = pickle.load(f)

In [32]:
some_cats

{'Scientist': 0,
 'NoOccupation': 1,
 'Teacher': 2,
 'Engineer': 3,
 'Entrepreneur': 4,
 'Developer': 5,
 'Lawyer': 6,
 'MediaManager': 7,
 'Doctor': 8,
 'Journalist': 9,
 'Manager': 10,
 'Accountant': 11,
 'Musician': 12,
 'Mechanic': 13,
 'Writer': 14,
 'Architect': 15}